### ISSUE TITLE
Document Future Updates

### ISSUE THREAD

**Issue by mlavin** [caktus/django-treenav#20]
I don't see a lot of feature development in the future of this project meaning that we should cut a v1.0 and establish a policy of updates related to Django/Django-MPTT updates going forward.

**Comment by vkurup** [comment]
I'm not sure that django-mptt is following any formal compatibility policy, but I guess I'd recommend that v1.0 would support django 1.8.X and django-mptt 0.7.X, and then tentatively have new point releases of django-treenav support new versions as they come out. Sound good?

**Comment by mlavin** [comment]
:+1:

**Comment by vkurup** [comment]
On that note, I should have also mentioned how I would plan to drop support for old versions. At this point, I think it makes sense to follow Django's lead. https://www.djangoproject.com/download/#supported-versions

That means dropping support for 1.4 (which ends extended support next month), 1.5, and 1.6. The main benefit at this point is removing the need to support both Django and South migrations.

**Comment by vkurup** [comment]
@benred42 has been implementing the above changes, which will be documented in the release notes.
