### ISSUE TITLE
Django 1.8 compatibility

### ISSUE THREAD

**Issue by vkurup** [caktus/django-treenav#40]
The tests are currently failing for Django trunk (slated to be version 1.8)

**Comment by benred42** [comment]
The tests are passing for 1.8 now, although there are still a few things that will be dropped in 1.10 (e.g. reversing urls by dotted path) that should probably be fixed.

**Comment by vkurup** [comment]
I'd recommend to create an issue for 1.10 deprecations and then go ahead and close this one.

**Comment by benred42** [comment]
Sounds good to me.  I'll go ahead and close this one.
