### ISSUE TITLE
coveralls fails locally

### ISSUE THREAD

**Issue by vkurup** [caktus/django-treenav#50]
With the change that we had to make for coveralls/tox2.0, we now run coveralls locally since it's in tox.ini. (Before it was only in .travis.yml). 

This fails for me locally because I don't have the tokens that Travis has:

```
You have to provide either repo_token in .coveralls.yml, or launch via Travis
ERROR: InvocationError: '/home/vkurup/dev/django-treenav/.tox/coverage/bin/coveralls'
```

I haven't figured out what the proper solution is yet... It would be nice to have coveralls run only on Travis, if that's possible.

**Comment by benred42** [comment]
Could we do that by calling coveralls after success in travis?
https://github.com/coagulant/coveralls-python#usage-travis-ci

**Comment by vkurup** [comment]
Yeah, I was hoping that it might just work to move coveralls to the the `after_success` block in Travis (as you suggested ^), so that coverage would still work locally, but coveralls only on Travis. I think it's a try-and-see-if-it-works, to see if the required env vars get passed to the after_success block.

**Comment by benred42** [comment]
I'll git a try and see what happens

**Comment by benred42** [comment]
Coverage should run locally now.

**Comment by vkurup** [comment]
Nice!
