### ISSUE TITLE
Delete from Admin changelist fails

### ISSUE THREAD

**Issue by benred42** [caktus/django-treenav#54]
Attempting to delete an item from the admin's changelist fails because it uses treenav's MenuItemManager instead of MPTT's TreeManager.  Deleting from the admin's change form, however, does work.

**Comment by benred42** [comment]
Copied from kkellydesign's comment on issue #42 : 
* In the list view (/admin/treenav/menuitem/), hit a checkbox and then choose "delete selected menu items", and confirm on the next screen. * error message: 'MenuItemManager' object has no attribute 'delay_mptt_updates'

**Comment by benred42** [comment]
So, making MenuItemManager inherit from TreeManager instead of models.Manager fixes this bug, but will doing that likely cause other issues?

**Comment by mlavin** [comment]
I looks like MPTT 0.4 -> 0.5 made this change https://github.com/django-mptt/django-mptt/blob/master/docs/upgrade.rst#042-to-055 It looks like MPTT expects `.objects` to be a `TreeManager` and I'm surprised we aren't seeing more problems with the current behavior. I think we should move forward with this change. There is a conflict in that both try to override `get_queryset` and that will need be resolved.

**Comment by benred42** [comment]
It looks like it should be possible to replicate the principle behavior of the TreeManager `get_queryset` method in our MenuItemManager.  All it's really doing is ordering the queryset.
