### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by itsdkey** [caktus/django-treenav#76]
Hi there,
Is this project still alive? I see that it has some issues with newer Django versions. Maybe it's possible to reactivate this app?

Any suggestions?

**Comment by Audiosutras** [comment]
Hello itsdkey. Thanks for your recent [PR](https://github.com/caktus/django-treenav/pull/75) and the project is being managed. We will have an opportunity to review your PR in the coming days.

**Comment by itsdkey** [comment]
Thanks for the answer. I'm looking forward for hearing from you.
