### ISSUE TITLE
Major update for Dj Treenav

### ISSUE THREAD

**Issue by itsdkey** [caktus/django-treenav#77]
I'm creating this issue so we can work on the major update of this package.

What is the problem?
DjTreenav does not support the newest Django and python versions (does not support officially) and it supports deprecated versions like python2.7-3.4, and Django 1.8.

To make this package up-to-date we should check and make adjustments so this package can be used with python3.6+ and Dj 2.2+

Based on that I want to suggest dropping support for deprecated versions so we can make the right and up-to-date changes that are followed in Django and Python.

To do that I think this should be done:
1. Based on the PR I've made and @Audiosutras suggestions ([link](https://github.com/caktus/django-treenav/pull/75#pullrequestreview-387713070)) we should offer a small database sample in our sample project so a User considering using DjTreenav can fully check it's potential without installing it in his project.
2. Restructure the project ([link](https://github.com/caktus/django-treenav/pull/75#issuecomment-609419353)) so we can run tests "the Django way" instead of creating mini hacks like run_tests.py
3. Update travis.yml and tox.ini to support the newest versions of Python and Django.
4. Updating the documentation if necessary.

To do that I suggest doing things in the following order: 3-2-1-4.

The only problem is that each point will depend on a different one, for example, to check if the code is okay we need to support python3.8 in tox and travis. So I think that theses points should be done on a single branch.

Any suggestions?

**Comment by vkurup** [comment]
This sounds like a reasonable game plan to me. Once these improvements are in place, we could publish a new release to PyPI.
